In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import pickle
from sklearn.linear_model import Ridge,Lasso,RidgeCV,LassoCV,ElasticNet,ElasticNetCV,LinearRegression
%matplotlib inline

In [2]:
df = pd.read_csv(r"C:\Users\krunal sheth\Downloads\Admission_Predict.csv")
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [3]:
df.shape

(400, 9)

In [4]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
df.drop(['Serial No.'],axis = 1, inplace = True)

In [7]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [8]:
y = df[['Chance of Admit ']]
y

Chance of Admit 
0                0.92
1                0.76
2                0.72
3                0.80
4                0.65
..                ...
395              0.82
396              0.84
397              0.91
398              0.67
399              0.95

[400 rows x 1 columns]

In [9]:
x = df.drop(['Chance of Admit '],axis = 1)
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
395        324          110                  3  3.5   3.5  9.04         1
396        325          107                  3  3.0   3.5  9.11         1
397        330          116                  4  5.0   4.5  9.45         1
398        312          103                  3  3.5   4.0  8.78         0
399        333          117                  4  5.0   4.0  9.66         1

[400 rows x 7 columns]

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
# standard scalerisation

scaler = StandardScaler()

In [12]:
arr = scaler.fit_transform(x)
arr

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [13]:
# convert array in to data structure
df1 = pd.DataFrame(arr)
df1

0         1         2         3         4         5         6
0    1.762107  1.746971  0.798829  1.093864  1.167321  1.764818  0.909112
1    0.627656 -0.067635  0.798829  0.596653  1.167321  0.455151  0.909112
2   -0.070467 -0.562528 -0.076600 -0.397769  0.052933 -1.005631  0.909112
3    0.453126  0.427257 -0.076600  0.099442 -1.061454  0.119339  0.909112
4   -0.244998 -0.727492 -0.952029 -1.392191 -0.504260 -0.653029 -1.099975
..        ...       ...       ...       ...       ...       ...       ...
395  0.627656  0.427257 -0.076600  0.099442  0.052933  0.740592  0.909112
396  0.714922 -0.067635 -0.076600 -0.397769  0.052933  0.858126  0.909112
397  1.151249  1.417042  0.798829  1.591075  1.167321  1.429006  0.909112
398 -0.419528 -0.727492 -0.076600  0.099442  0.610127  0.304036 -1.099975
399  1.413045  1.582006  0.798829  1.591075  0.610127  1.781609  0.909112

[400 rows x 7 columns]

In [14]:
df1.describe()

0             1             2             3             4  \
count  4.000000e+02  4.000000e+02  4.000000e+02  4.000000e+02  4.000000e+02   
mean  -4.174439e-16  5.595524e-16  7.105427e-17  7.993606e-17 -1.332268e-16   
std    1.001252e+00  1.001252e+00  1.001252e+00  1.001252e+00  1.001252e+00   
min   -2.339367e+00 -2.542098e+00 -1.827457e+00 -2.386613e+00 -2.733036e+00   
25%   -7.685900e-01 -7.274920e-01 -9.520286e-01 -8.949798e-01 -5.042604e-01   
50%    1.679859e-02 -6.763531e-02 -7.660001e-02  9.944220e-02  5.293342e-02   
75%    7.149218e-01  7.571856e-01  7.988286e-01  5.966532e-01  6.101273e-01   
max    2.023903e+00  2.076899e+00  1.674257e+00  1.591075e+00  1.724515e+00   

                  5             6  
count  4.000000e+02  4.000000e+02  
mean   7.771561e-16 -3.996803e-17  
std    1.001252e+00  1.001252e+00  
min   -3.020504e+00 -1.099975e+00  
25%   -7.201909e-01 -1.099975e+00  
50%    1.859559e-02  9.091117e-01  
75%    7.783704e-01  9.091117e-01  
max    2.218165e+00  9.091117e-01

In [15]:
# divde data in to training and testing

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(arr, y, test_size=0.25, random_state=80)

In [17]:
# build linear Regression model

In [18]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [19]:
lr.fit(x_train,y_train)

LinearRegression()

# save model 

In [20]:
pickle.dump(lr,open('admission_lr_model.pickel','wb'))

In [21]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 10B0-EB93

 Directory of C:\Users\krunal sheth\Rushali\Machine Learning

05/26/2025  12:10 PM    <DIR>          .
05/26/2025  12:10 PM    <DIR>          ..
05/26/2025  12:10 PM    <DIR>          .ipynb_checkpoints
05/26/2025  01:08 PM               525 admission_lr_model.pickel
05/22/2025  02:30 PM           170,871 Admission_Predict.ipynb
05/26/2025  12:04 PM             2,771 large_scale_wave_energy_Farm_lr_model.pickel
05/26/2025  12:10 PM           179,344 Large-scale Wave Energy Farm.ipynb
05/21/2025  10:33 AM            11,924 placement data analysis using class and function .ipynb
05/21/2025  03:06 PM            96,563 placement data analysis.ipynb
               6 File(s)        461,998 bytes
               3 Dir(s)  49,070,964,736 bytes free


# prediction

In [22]:
lr.predict([[1.762107,1.746971,0.798829,1.093864,1.167321,1.764818,0.909112]])

array([[0.9451902]])

In [23]:
lr.predict([[0.627656,-0.067635,0.798829,0.596653,1.167321,0.455151,0.909112]])

array([[0.80424604]])

In [24]:
lr.predict([[-0.070467,-0.562528,-0.076600,-0.397769,0.052933,-1.005631,0.909112]])

array([[0.6572108]])

# use saved pickle model

In [25]:
model = pickle.load((open('admission_lr_model.pickel','rb')))

In [26]:
model

LinearRegression()

In [27]:
model.predict([[1.762107,1.746971,0.798829,1.093864,1.167321,1.764818,0.909112]])

array([[0.9451902]])

In [28]:
model.predict([[0.627656,-0.067635,0.798829,0.596653,1.167321,0.455151,0.909112]])

array([[0.80424604]])

In [29]:
model.predict([[-0.070467,-0.562528,-0.076600,-0.397769,0.052933,-1.005631,0.909112]])

array([[0.6572108]])

In [30]:
base_preds = lr.predict(arr)
base_preds

array([[0.9451902 ],
       [0.80424605],
       [0.6572108 ],
       [0.73883095],
       [0.63909288],
       [0.86707271],
       [0.7130213 ],
       [0.60663172],
       [0.55316149],
       [0.7180439 ],
       [0.73265417],
       [0.83561172],
       [0.85148466],
       [0.64414114],
       [0.63947983],
       [0.64996074],
       [0.71518968],
       [0.65586251],
       [0.73686763],
       [0.65531272],
       [0.61709096],
       [0.70502063],
       [0.92459353],
       [0.95580164],
       [0.9519853 ],
       [0.95865586],
       [0.76639424],
       [0.52714098],
       [0.43522778],
       [0.49863968],
       [0.60248546],
       [0.71507815],
       [0.92173844],
       [0.93199625],
       [0.95390544],
       [0.85975517],
       [0.66015211],
       [0.54818863],
       [0.50692305],
       [0.59045026],
       [0.64975136],
       [0.65496742],
       [0.6792194 ],
       [0.84250487],
       [0.88171869],
       [0.83139216],
       [0.89996548],
       [0.936

In [31]:
y_pred = model.predict(x_test)

In [32]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print(mean_absolute_error(y_test,y_pred))
print(np.sqrt(mean_squared_error(y_test,y_pred)))

0.04755534265221963
0.06167282278015035


In [33]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

print('MAE:',mean_absolute_error(y_test,y_pred))
print('MSE:',mean_squared_error(y_test,y_pred))
print('R2 score:',r2_score(y_test,y_pred))

MAE: 0.04755534265221963
MSE: 0.003803537069671832
R2 score: 0.8421506860195953


In [34]:
y_test.mean()

Chance of Admit     0.728
dtype: float64

In [35]:
lr.coef_

array([[ 0.01950838,  0.01759474,  0.00935251, -0.00202189,  0.01839557,
         0.06710914,  0.00948029]])

In [36]:
lr.intercept_

array([0.72628984])

In [37]:
lr.score(x_test,y_test)

0.8421506860195953

# Adjusted R2

In [38]:
x.shape

(400, 7)

In [39]:
n = x.shape[0]
n

400

In [40]:
# created adjusted R2 function
def adj_r2(x,y):
    r2 = lr.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1 - (1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [41]:
adj_r2(x_test,y_test)

0.830140412129782

# variation inflation factor

In [42]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [43]:
vif_df = pd.DataFrame()

In [44]:
vif_df['vif'] = [variance_inflation_factor(arr,i) for i in range(arr.shape[1])]
vif_df

vif
0  4.615516
1  4.288959
2  2.919606
3  3.075504
4  2.431258
5  5.207403
6  1.543312

In [45]:
vif_df['feature']= x.columns
vif_df

vif            feature
0  4.615516          GRE Score
1  4.288959        TOEFL Score
2  2.919606  University Rating
3  3.075504                SOP
4  2.431258               LOR 
5  5.207403               CGPA
6  1.543312           Research

# Regularization

In [46]:
# Linear Regression with Lasso
lassocv = LassoCV(cv=10, max_iter = 200000)
lassocv.fit(x_train, y_train)

C:\Users\krunal sheth\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1656: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV(cv=10, max_iter=200000)

In [47]:
lassocv.alpha_

0.0008886142314761828

In [48]:
lasso = Lasso(alpha = lassocv.alpha_)
lasso.fit(x_train, y_train)

Lasso(alpha=0.0008886142314761828)

In [49]:
y_pred = lasso.predict(x_test)
print('MSE:',mean_squared_error(y_test,y_pred))

MSE: 0.0038465083695619186


In [50]:
# Linear Regression with Ridge
ridgecv = RidgeCV(alphas = np.random.uniform(0,10,50),cv=10)
ridgecv.fit(x_train, y_train)

RidgeCV(alphas=array([2.13617609, 7.17870689, 8.67185709, 3.15650239, 1.14118915,
       3.70266798, 6.04532878, 5.66154612, 3.06193608, 3.48446867,
       4.37409151, 3.09235595, 8.85969597, 2.48134305, 5.66241822,
       5.06839175, 5.63427672, 2.22094954, 5.36599073, 4.57935162,
       3.46744083, 9.71740699, 0.27699702, 2.77076736, 5.08498864,
       3.22677428, 2.56323416, 3.77983721, 9.34608397, 1.94641986,
       2.41157537, 6.72640745, 9.43795167, 6.02154962, 4.86262786,
       1.87597162, 9.08262864, 9.76333831, 8.74061968, 9.3359799 ,
       7.71859274, 5.66829004, 4.98300301, 7.05030189, 0.10692759,
       5.75745805, 4.60505261, 5.06121948, 6.0658898 , 0.04801458]),
        cv=10)

In [51]:
ridgecv.alpha_

9.763338311162737

In [52]:
ridge_lr = Ridge(alpha = ridgecv.alpha_)
ridge_lr.fit(x_train, y_train)

Ridge(alpha=9.763338311162737)

In [53]:
y_pred = ridge_lr.predict(x_test)
print('MSE:',mean_squared_error(y_test,y_pred))

MSE: 0.0038845323236657648


# ElasticNet

In [54]:
# create linear regression with elasticNet
elastic = ElasticNetCV(alphas = None, cv = 10)
elastic.fit(x_train, y_train)

C:\Users\krunal sheth\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1656: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ElasticNetCV(cv=10)

In [55]:
elastic.alpha_

0.001657449212725497

In [56]:
elastic.l1_ratio_

0.5

In [59]:
elastic_lr = ElasticNet(alpha = elastic.alpha_, l1_ratio = elastic.l1_ratio_ )
elastic_lr.fit(x_train, y_train)

ElasticNet(alpha=0.001657449212725497)

In [62]:
model = ElasticNet(alpha = 1.0,l1_ratio = 0.5)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
MSE = mean_squared_error(y_test,y_pred)

print("mean_squared_error: ", MSE)
print("coefficients:", model.coef_)

mean_squared_error:  0.024119684444444442
coefficients: [0. 0. 0. 0. 0. 0. 0.]
